export const UI_ACTIONS = {
  CLOSE_COLLAPSE_SIDE_NAV: 'CLOSE_COLLAPSE_SIDE_NAV',
  CLOSE_RESPONSIVE_NAV: 'CLOSE_RESPONSIVE_NAV',
  SET_LANGUAGE: 'SET_LANGUAGE',
  TOGGLE_COLLAPSE_SIDE_NAV: 'TOGGLE_COLLAPSE_SIDE_NAV',
  TOGGLE_RESPONSIVE_NAV: 'TOGGLE_RESPONSIVE_NAV'
};
